-- INSERT INTO burgers (burger_name) VALUES ('Cheeseburger');
-- INSERT INTO burgers (burger_name) VALUES ('Mushroom Swiss');
-- INSERT INTO burgers (burger_name, devoured) VALUES ('Bacon Cheeseburger', true);
-- INSERT INTO burgers (burger_name, devoured) VALUES ('Lamb Burger', true);
-- INSERT INTO burgers (burger_name, devoured) VALUES ('Western BBQ Burger', true);
-- INSERT INTO burgers (burger_name) VALUES ('Spicy Chicken Fried Sandwich');